[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
  'php artisan config:clear',
  'php artisan cache:clear'
]

[start]
cmd = 'sh deploy-start.sh'
